#!/usr/bin/env bash

os="$1"
pkg="$2"
external_pkg_name="$3"

home_dir=~/
setup_dir="$home_dir/personal/config/setup"
this_dir="$setup_dir/utils"

if [ -z "$external_pkg_name" ]; then
    external_pkg_name="$pkg"
fi

pkg_is_installed=$($this_dir/is_already_installed "$pkg")

if [[ $pkg_is_installed == "False" ]]; then
    if [ "$os" == "mac" ]; then
        brew_is_installed=$($this_dir/is_already_installed brew)

        if [[ $brew_is_installed == "False" ]]; then
            echo "❌ Homebrew is not installed. Please install Homebrew first."
            exit 1
        fi

        echo "🔧 Installing $pkg..."
        brew install "$external_pkg_name"
    else
        echo "🔧 Installing $pkg..."
        if [ "$os" == "arch" ]; then
            sudo pacman -Sy "$external_pkg_name"
        elif [ "$os" == "fedora" ]; then
            sudo dnf install -y "$external_pkg_name"
        elif [ "$os" == "alpine" ]; then
            sudo apk add "$external_pkg_name"
        elif [ "$os" == "redhat" ]; then
            sudo yum install -y "$external_pkg_name"
        elif [ "$os" == "suse" ]; then
            sudo zypper install -y "$external_pkg_name"
        elif [ "$os" == "freebsd" ]; then
            sudo pkg install -y "$external_pkg_name"
        elif [ "$os" == "debian" ]; then
            sudo apt install -y "$external_pkg_name"
        elif [ "$os" == "windows" ]; then
            choco install "$external_pkg_name" -y
        fi
    fi
else
    echo "✅ $pkg is already installed."
fi
