#!/usr/bin/env bash

pkg="$1"
external_pkg_name="$2"

home_dir=~/
setup_dir="$home_dir/personal/config/setup"
this_dir="$setup_dir/utils"

if [ -z "$external_pkg_name" ]; then
    external_pkg_name="$pkg"
fi

pkg_is_installed=$($this_dir/is_already_installed npm)

if [[ "$($this_dir/utils/is_already_installed npm)" == "False" ]]; then
    echo "❌ Node and NPM is not installed. Please install Node and NPM first."
    exit 1
fi

pkg_is_installed=$($this_dir/is_already_installed "$pkg")

if [[ $pkg_is_installed == "False" ]]; then
    echo "🔧 Installing $pkg via npm..."
    npm i -g "$external_pkg_name"
else
    echo "✅ $pkg is already installed."
fi
