#!/usr/bin/env bash

command=$1
current_file="$(readlink -f "$0")"
current_dir="$(dirname "$current_file")"
config_dir="$(cd "$current_dir/../../" && pwd -P)"
my_ghostty_config_dir="$config_dir/ghostty"
system_config_dir="$HOME/.config"
old_ghostty_config_dir="$system_config_dir/ghostty"
backup_dir="$config_dir/dot_files/backups"

if [[ "$command" == "reset" ]]; then
    echo "Resetting to previous Ghostty config..."
    cp -r "$backup_dir/ghostty" "$system_config_dir"
else 
    echo "Backing up current Ghostty config..."
    cp -r "$old_ghostty_config_dir" "$backup_dir"
    echo "Copying my Ghostty config to system config directory..."
    cp -r "$my_ghostty_config_dir" "$system_config_dir"
fi
