#!/usr/bin/env bash

command=$1
current_file="$(readlink -f "$0")"
current_dir="$(dirname "$current_file")"
config_dir="$(cd "$current_dir/../../" && pwd -P)"
my_starship_config_dir="$config_dir/starship"
system_config_dir="$HOME/.config"
old_starship_config_file="$system_config_dir/starship.toml"
backup_dir="$config_dir/dot_files/backups"
run_confirm="$config_dir/dot_files/utils/run_confirm_command"
parse_arg="$config_dir/dot_files/utils/parse_arg"

reset=$($parse_arg "reset" "$@")
yes_to_all=$($parse_arg "yes-to-all" "$@")
dry_run=$($parse_arg "dry-run" "$@")

if [[ "$yes_to_all" == true ]]; then
    yes_to_all="--yes"
else
    yes_to_all=""
fi
if [[ "$dry_run" == true ]]; then
    dry_run="--dry-run"
else
    dry_run=""
fi

if [[ "$reset" == true ]]; then
    echo "Resetting to previous Starship config..."
    $run_confirm "$yes_to_all" "$dry_run" -- cp "$backup_dir/starship.toml" "$system_config_dir/starship.toml" || exit 1
else 
    if [[ -f "$old_starship_config_file" ]]; then
        echo "Backing up current Starship config file..."
        $run_confirm "$yes_to_all" "$dry_run" -- cp "$old_starship_config_file" "$backup_dir/starship.toml" || exit 1
    fi
    echo "Copying my Starship config file to system config directory..."
    $run_confirm "$yes_to_all" "$dry_run" -- cp "$my_starship_config_dir/starship.toml" "$system_config_dir/starship.toml" || exit 1
fi

