#!/usr/bin/env bash

command=$1
current_file="$(readlink -f "$0")"
current_dir="$(dirname "$current_file")"
config_dir="$(cd "$current_dir/../../" && pwd -P)"
my_tmux_config_dir="$config_dir/tmux"
backup_dir="$config_dir/dot_files/backups"

if [[ "$command" == "reset" ]]; then
    echo "Resetting to previous tmux config..."
    cp "$backup_dir/tmux.conf" "$HOME/.tmux.conf"
else 
    echo "Backing up current tmux config file..."
    cp "$HOME/.tmux.conf" "$backup_dir/tmux.conf"
    echo "Copying my tmux config file to system config directory..."
    cp "$my_tmux_config_dir/tmux.conf" "$HOME/.tmux.conf"
fi

