#!/usr/bin/env bash

command=$1
current_file="$(readlink -f "$0")"
current_dir="$(dirname "$current_file")"
config_dir="$(cd "$current_dir/../../" && pwd -P)"
my_zsh_config_dir="$config_dir/zsh"
backup_dir="$config_dir/dot_files/backups"

if [[ "$command" == "reset" ]]; then
    echo "Resetting to previous zsh config..."
    cp "$backup_dir/zshrc" "$HOME/.zshrc"
else 
    echo "Backing up current zsh config file..."
    cp "$HOME/.zshrc" "$backup_dir/zshrc"
    echo "Copying my zsh config file to system config directory..."
    cp "$my_zsh_config_dir/zshrc" "$HOME/.zshrc"
fi

