#!/usr/bin/env bash

OS="OSX"

if [[ $OS == "OSX" ]]; then 
    xcode-select --install
    which brew 1> /dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

