#!/usr/bin/env bash

OS=$(~/personal/config/setup/tasks-old/os.sh)
HOME_DIR=~/
CURRENT_DIR=$(pwd)

if [[ $OS == "LINUX" ]]; then
    sudo apt install zsh
fi

if [[ $OS == "LINUX" ]] || [[ $OS == "OSX" ]]; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    ln -sf $CURRENT_DIR/oh-my-zsh-themes/danielshields.zsh-theme $HOME_DIR/.oh-my-zsh/themes/danielshields.zsh-theme
    ln -sf $CURRENT_DIR/.zshrc $HOME_DIR/.zshrc

    # TODO: install any plugins here
    # - name: Install zsh-autosuggestions
    #   ansible.builtin.git:
    #     repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    #     dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
fi

