if [ -f ~/bash_profile ]; then
    source $HOME/.bash_profile
fi

export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

if [ -f ~/.oh-my-zsh/themes/danielshields.zsh-theme ]; then
    ZSH_THEME="danielshields"
else
    ZSH_THEME="robbyrussell"
fi

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
if [ -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
    plugins=(git zsh-autosuggestions)
else
    plugins=(git)
fi

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

if which nvim >/dev/null; then
    export VISUAL=nvim
    export VIMCONFIG=~/.config/nvim
    export VIMDATA=~/.local/share/nvim

    # vim aliases
    alias vimlog="rm -rf ~/.local/state/nvim/log && rm -rf ~/.local/state/nvim/lsp.log && rm -rf ~/.local/state/nvim/mason.log"
    alias vim=nvim
    alias vi=nvim
fi

# save your bacon rm alias
alias rm="rm -rfi"

if which exa >/dev/null; then
    # ls aliases
    alias ls="exa"
    alias la="exa -lah"
    alias ll="exa -lah"
    alias tree="exa --tree"
fi

if which bat >/dev/null; then
    # cat alias
    alias cat="bat"
fi

if which brew >/dev/null; then
    alias bud="brew update && brew upgrade && brew doctor && brew cleanup"
fi

# Git aliases
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gbranches="git branch -a | cat"

# Add important scripts to PATH
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/personal/private-scripts/bash:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export PATH="$HOME/Library/Python/3.9/bin:$PATH"

# NVIM stuff
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# auto complete suggestion from zsh-autosuggestions
bindkey ^a autosuggest-accept

if which zoxide >/dev/null; then
    # cd aliases
    alias cd="z"
    alias zz="z -"
    # add zoxide to shell
    eval "$(zoxide init zsh)"
fi

if which python3 >/dev/null; then
    alias python="python3"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# bindings to call custom scripts
bindkey -s ^f "project-selector\n"
bindkey -s ^s "cheatsheet\n"
bindkey -s ^t "run\n"

if which ng >/dev/null; then
    # Load Angular CLI autocompletion.
    source <(ng completion script)
fi

set -o vi

eval "$(starship init zsh)"

JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home"
export PATH="${JAVA_HOME}/bin:${PATH}"

export M2_HOME="/Users/danielshields/apache-maven-3.9.8"
export PATH="${M2_HOME}/bin:${PATH}"

# Created by `pipx` on 2025-02-26 15:40:28
export PATH="$PATH:/Users/danielshields/.local/bin"

export PATH="/opt/homebrew/bin/bash:$PATH"

# yazi setup
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

[ -f "/Users/danielshields/.ghcup/env" ] && . "/Users/danielshields/.ghcup/env" # ghcup-env
export PATH="/opt/homebrew/bin:$PATH"
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/daniel.shields/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
